os: linux
dist: focal
language: node_js
node_js: 12
env: CC=clang CXX=clang++ npm_config_clang=1 USE_SYSTEM_FPM=true
compiler: clang

arch:
  - arm64

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - libopenjp2-tools 
      - xz-utils
      - rpm
      - ruby
      - ruby-dev
      - build-essential

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi

cache: yarn

install:
  - yarn

after_success:
  - (git branch --contains $TRAVIS_COMMIT | grep canary > /dev/null || [[ "$TRAVIS_BRANCH" == "canary" ]] ) && (cd build; cp canary.icns icon.icns; cp canary.ico icon.ico)
  - gem install --no-document fpm -v 1.10.2
  - yarn run dist

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

deploy:
  provider: releases
  file_glob: true
  file: dist/*
  edge: true # opt in to dpl v2
  token: $GITHUB_RELEASE_KEY
  on:
    tags: true