name: Node CI

on: [push]
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: yarn install, build, and test
      run: |
        yarn install
        yarn run build
        yarn test
      env:
        CI: true
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: node-gyp config (windows)
      run: |
        npm install --global --production windows-build-tools
    - name: yarn config
      run: |
        yarn config set msvs_version 2015
    - name: yarn install, build, and test
      run: |
        yarn install
        yarn run build
        yarn test
      env:
        CI: true
